[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

; Linux (CachyOS/Arch): Arduino Uno aparece en /dev/ttyACM0
; Si no sube: sudo usermod -aG uucp $USER && reiniciar sesión
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0
upload_flags = -V

build_src_filter = +<main.cpp>   ; solo compilar main.cpp — los .cpp OOP en subdirs quedan como referencia

build_flags =
    -I include         ; headers separados en include/
    -Wall              ; habilitar todos los warnings

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
